import type { Metadata } from "next";
import { Alegreya, Mulish } from "next/font/google";
import { headers } from "next/headers";
import Navbar from "../components/layout/Navbar";
import userApi from "../service/users/users.service";
import "./globals.css";

const mulish = Mulish({ subsets: ["latin"], variable: "--font-mulish" });
const alegreya = Alegreya({ subsets: ["latin"], variable: "--font-alegreya" });

export const metadata: Metadata = {
  title: "X Clone",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const accessToken = (await headers().get("x-social-access-token")) ?? null;
  const currentUser = accessToken
    ? await userApi.getMeInternal(accessToken)
    : undefined;

  return (
    <html lang="en" className={`${alegreya.variable} ${mulish.variable}`}>
      <body>
        <Navbar
          loggedUsername={currentUser?.username}
          photoUrl={currentUser?.photoUrl}
        />
        {children}
      </body>
    </html>
  );
}
